"use client";

import React from 'react';
import { Leaf, Sun, ShieldAlert, Sparkles } from 'lucide-react';

export default function SustainabilityPage() {
  const points = [
    {
      icon: <Sun className="w-6 h-6 text-amber-500" />,
      title: "100% Green Web Hosting",
      desc: "Our server node clusters are powered strictly by renewable solar and wind energy grids in Northern Europe, maintaining a near-zero carbon footprint."
    },
    {
      icon: <Leaf className="w-6 h-6 text-emerald-500" />,
      title: "Carbon-Neutral Digital Transactions",
      desc: "We offset double the carbon emissions generated by every customer search, dynamic image watermark rendering, and invoice payment transaction."
    },
    {
      icon: <ShieldAlert className="w-6 h-6 text-indigo-400" />,
      title: "Optimized File Compression",
      desc: "Our custom AI thumbnail model reduces file sizes on hard disk servers by 45%, reducing heat and overall data center electricity utilization."
    }
  ];

  return (
    <div className="relative max-w-5xl mx-auto px-4 py-16 sm:py-20 select-none">
      
      {/* Glow background */}
      <div className="glow-spot-cyan top-[10%] right-[10%]" />

      {/* Header */}
      <div className="text-center mb-16">
        <div className="inline-flex items-center gap-1.5 px-4 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-5">
          <Leaf className="w-3.5 h-3.5 text-emerald-450" />
          <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-widest">Environmental Oath</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight mb-4">
          Eco-Friendly Digital Footprint
        </h1>
        <p className="text-xs sm:text-sm text-gray-500 max-w-xl mx-auto leading-relaxed font-semibold">
          Desenio Group is committed to environmental conservation. We actively minimize computing footprints across our global API networks.
        </p>
      </div>

      {/* Grid Points */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-stretch mb-16">
        {points.map((p, idx) => (
          <div key={idx} className="glass-card rounded-2xl p-6 text-center flex flex-col justify-between items-center">
            <div>
              <div className="w-12 h-12 rounded-full bg-gray-950/60 border border-gray-900 flex items-center justify-center mb-5">
                {p.icon}
              </div>
              <h3 className="text-xs font-bold text-white uppercase tracking-wider mb-2 leading-relaxed">{p.title}</h3>
              <p className="text-xs text-gray-400 leading-relaxed font-medium">{p.desc}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Commitment Card */}
      <div className="glass-card rounded-3xl p-8 max-w-2xl mx-auto text-center border-emerald-500/10">
        <h3 className="text-base font-extrabold text-white mb-2">Our 2030 Sustainability Target</h3>
        <p className="text-xs text-gray-400 leading-relaxed font-medium">
          Đạt mục tiêu giảm trừ hoàn toàn phát thải Carbon gián tiếp (Scope 3) từ việc lưu trữ hình ảnh trên đám mây bằng cách chuyển dịch sang hệ thống ổ cứng tự hủy sinh học và máy chủ tuần hoàn tự nhiên.
        </p>
      </div>

    </div>
  );
}
